### ISSUE TITLE
Backdrop drush commands

### ISSUE THREAD

**Issue by jimmynash** [docksal/example-backdrop#3]
So normally I would run "fin drush {drush-command}" to get drush to do it's thing.

With backdrop there is a project that adds commands to Drush 8 for backdrop. 

Is it possible to add this or is there a way I can add them manually?

https://github.com/backdrop-contrib/drush

**Comment by sean-e-dietrich** [comment]
@jimmynash there are a few different was you could tackle this.

Create a folder within your project `.docksal/etc/drush/commands` add the backdrop commands into that folder.

Then within your `.docksal/docksal.yml` it would need to look similar to this

```
# Basic LAMP stack

version: "2.1"

services:
  # Web
  web:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: web
    depends_on:
      - cli

  # DB
  db:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: db

  # CLI
  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    environment:
      - VIRTUAL_HOST
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/drush:/etc/drush:ro
```

Even though the documentation says to use `~/.drush/commands` I believe that will work as well.
